import test from 'node:test';
import assert from 'node:assert/strict';
import {createRelayState,relayReducer as step,canEnter,restoreRelayState,PROGRAMS,nextAction,minutesAt,clockLabel} from '../src/relay-model.js';
function prepared(){let s=createRelayState();for(const a of [{type:'GO',index:1},{type:'ORDER'},{type:'EAT'},{type:'GO',index:2},{type:'PAY',method:'card'},{type:'SCAN'},{type:'GO',index:3},{type:'REDEEM'}])s=step(s,a);return s;}
test('receipt and coupon require a meal and cannot be redeemed twice',()=>{let s=createRelayState();assert.equal(step(s,{type:'SCAN'}),s);assert.equal(step(s,{type:'GO',index:3}),s);s=prepared();assert.equal(s.coupon,'used');assert.equal(step(s,{type:'REDEEM'}),s);assert.equal(step(s,{type:'GO',index:4}),s);});
test('scan failure can be retried without creating duplicate coupons',()=>{let s=createRelayState();for(const a of [{type:'GO',index:1},{type:'ORDER'},{type:'EAT'},{type:'GO',index:2},{type:'PAY',method:'card'},{type:'SCAN',valid:false}])s=step(s,a);assert.equal(s.coupon,'none');assert.equal(s.scanError,true);s=step(s,{type:'SCAN',valid:true});assert.equal(s.coupon,'issued');assert.equal(s.scanError,false);assert.equal(step(s,{type:'SCAN'}),s);});
for(const id of Object.keys(PROGRAMS))test(`${id} completes in three actions and survives navigation/reload`,()=>{let s=step(prepared(),{type:'PROGRAM',id});for(let i=0;i<3;i++)s=step(s,{type:'CRAFT'});assert.deepEqual(s.completedPrograms,[id]);assert.equal(step(s,{type:'CRAFT'}),s);s=step(s,{type:'GO',index:4});assert.equal(canEnter(s,5),false);s=step(s,{type:'ARRIVE'});s=step(s,{type:'GO',index:5});s=step(s,{type:'WALK'});s=step(s,{type:'GO',index:6});s=step(s,{type:'BUY',id:'food'});assert.equal(step(s,{type:'BUY',id:'food'}),s);s=step(s,{type:'FINISH'});assert.equal(s.finished,true);assert.deepEqual(restoreRelayState(JSON.stringify(s)),s);assert.deepEqual(step(s,{type:'RESET'}),createRelayState());});
test('all programs remain completed when switching and repeating',()=>{let s=prepared();for(const id of Object.keys(PROGRAMS)){s=step(s,{type:'PROGRAM',id});for(let i=0;i<3;i++)s=step(s,{type:'CRAFT'});}s=step(s,{type:'PROGRAM',id:'mask'});assert.equal(s.craftSteps,3);assert.equal(s.completedPrograms.length,3);assert.equal(nextAction(s).index,4);});
test('malformed stored state and navigation never bypass progress',()=>{assert.deepEqual(restoreRelayState('bad'),createRelayState());const s=restoreRelayState(JSON.stringify({version:1,stage:6,coupon:'used',arrived:true,bridgeWalked:true,cart:['food']}));assert.equal(s.coupon,'none');assert.equal(s.arrived,false);assert.equal(s.finished,false);assert.equal(canEnter(s,6),false);assert.equal(step(s,{type:'GO',index:NaN}),s);});
test('finish requires engagement and game is limited to three throws',()=>{let s=prepared();for(let i=0;i<3;i++)s=step(s,{type:'CRAFT'});for(const a of [{type:'GO',index:4},{type:'ARRIVE'},{type:'GO',index:5},{type:'WALK'},{type:'GO',index:6}])s=step(s,a);assert.equal(step(s,{type:'FINISH'}),s);for(let i=0;i<5;i++)s=step(s,{type:'THROW',hit:true});assert.equal(s.gameAttempts,3);assert.equal(s.gameScore,3);assert.equal(step(s,{type:'FINISH'}).finished,true);});

test('switching programs preserves partial work, color and the original coupon recipient',()=>{let s=prepared();s=step(s,{type:'COLOR',color:'#4a8274'});s=step(s,{type:'CRAFT'});s=step(s,{type:'PROGRAM',id:'tea'});s=step(s,{type:'CRAFT'});s=restoreRelayState(JSON.stringify(s));assert.equal(s.redeemedProgram,'mask');assert.equal(s.craftSteps,1);s=step(s,{type:'PROGRAM',id:'mask'});assert.equal(s.craftSteps,1);assert.equal(s.paintColor,'#4a8274');});
test('the itinerary adds every completed experience without double counting',()=>{let s=prepared();for(const id of Object.keys(PROGRAMS)){s=step(s,{type:'PROGRAM',id});for(let i=0;i<3;i++)s=step(s,{type:'CRAFT'});}assert.equal(clockLabel(minutesAt({...s,stage:4})),'20:00');assert.equal(clockLabel(minutesAt({...s,stage:5})),'20:20');s=step(s,{type:'PROGRAM',id:'mask'});assert.equal(clockLabel(minutesAt({...s,stage:4})),'20:00');});
test('empty reload stays on the cover and invalid chapter numbers are rejected',()=>{const s=createRelayState();assert.deepEqual(restoreRelayState(JSON.stringify(s)),s);for(const index of [-1,-20,7,1.5])assert.equal(step(s,{type:'GO',index}),s);});
test('painted artwork survives refresh and rejects non-image or oversized URLs',()=>{let s=prepared();const image='data:image/png;base64,iVBORw0KGgo=';s=step(s,{type:'ART',image});assert.equal(s.maskArt,image);assert.equal(restoreRelayState(JSON.stringify(s)).maskArt,image);assert.equal(step(s,{type:'ART',image:'javascript:alert(1)'}),s);assert.equal(step(s,{type:'ART',image:'data:image/png;base64,'+'A'.repeat(400000)}),s);});
