import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {gzipSync} from 'node:zlib';
import {createStaticServer} from '../server.mjs';

test('production server compresses text, revalidates stable assets and preserves raw gzip URLs',async t=>{
  const directory=await mkdtemp(join(tmpdir(),'andong-static-'));
  const server=createStaticServer(directory);
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));await rm(directory,{recursive:true,force:true});});
  await mkdir(join(directory,'assets'));const data=JSON.stringify({name:'안동',items:Array(100).fill('지도')});
  await writeFile(join(directory,'index.html'),'<h1>안동</h1>');
  await writeFile(join(directory,'data.json'),data);await writeFile(join(directory,'data.json.gz'),gzipSync(data));
  await writeFile(join(directory,'assets/image.jpg'),'photo');await writeFile(join(directory,'assets/app-Abcd1234.js'),'export const ready=true;');
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
  const compressed=await fetch(base+'/data.json');
  assert.equal(compressed.headers.get('content-encoding'),'gzip');assert.equal(compressed.headers.get('vary'),'Accept-Encoding');
  assert.ok(Number(compressed.headers.get('content-length'))<Buffer.byteLength(data));assert.equal(await compressed.text(),data);
  const cached=await fetch(base+'/data.json',{headers:{'if-none-match':compressed.headers.get('etag')}});
  assert.equal(cached.status,304);assert.equal(await cached.text(),'');
  const raw=await fetch(base+'/data.json',{headers:{'accept-encoding':'gzip;q=0'}});
  assert.equal(raw.headers.get('content-encoding'),null);assert.equal(await raw.text(),data);
  assert.notEqual(raw.headers.get('etag'),compressed.headers.get('etag'));
  const explicit=await fetch(base+'/data.json.gz');assert.equal(explicit.headers.get('content-encoding'),null);
  assert.deepEqual(Buffer.from(await explicit.arrayBuffer()),gzipSync(data));
  const photo=await fetch(base+'/assets/image.jpg');assert.equal(photo.headers.get('cache-control'),'no-cache');await photo.arrayBuffer();
  const unchanged=await fetch(base+'/assets/image.jpg',{headers:{'if-none-match':photo.headers.get('etag')}});assert.equal(unchanged.status,304);
  await writeFile(join(directory,'assets/image.jpg'),'updated photo');
  const changed=await fetch(base+'/assets/image.jpg',{headers:{'if-none-match':photo.headers.get('etag')}});assert.equal(changed.status,200);assert.equal(await changed.text(),'updated photo');
  const bundle=await fetch(base+'/assets/app-Abcd1234.js',{method:'HEAD'});assert.match(bundle.headers.get('cache-control'),/immutable/);assert.equal(await bundle.text(),'');
  assert.equal((await fetch(base+'/absent')).status,404);assert.equal((await fetch(base+'/',{method:'POST'})).status,405);
});
